### PR TITLE
Upgrade Kafka version

### PR DESCRIPTION
**Pull request by aliok**
Upgrade Kafka version. Although in SO we use 3.4.x, for some reason AMQ Streams complain about that here.
Instead I am using 3.3.x

### CODE REVIEW

**Comment by pierDipi** [comment]
You might need to update `log.message.format.version` too

**Comment by aliok** [comment]
/test 412-test-kafka-7465737-aws-ocp-412

```
Reconcile workers to at least 15 nodes
Additional replicas 12
machineset.machine.openshift.io/ci-ocp-4-12-amd64-aws-t4ql6-worker-us-east-1a scaled
error: readyReplicas is not found
```

**Comment by aliok** [comment]
```
message: 'Unsupported Kafka.spec.kafka.version: 3.0.0. Supported versions are:
[3.2.3, 3.3.1]'
```

Gonna use 3.3.1 as AMQ streams product doesn't support 3.4.0

**Review by creydr — APPROVED** [review]
/lgtm

**Pull request merged**
