### PR TITLE
Add scripts documentation

### PR DESCRIPTION
**Pull request by pierDipi**
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by matzew** [comment]
How about adding some `README`, that briefly show how to run the commands ?

**Comment by pierDipi** [comment]
Slowly getting there!

**Comment by pierDipi** [comment]
This PR is still valid on its own though

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
